### ISSUE TITLE
The extention adds "configurationProvider": "ms-vscode.cmake-tools" even if I use meson

### ISSUE THREAD

**Issue by intractabilis** [xpack/vscode-xpack-extension-ts#17]
The extension forcefully adds property
```
"configurationProvider": "ms-vscode.cmake-tools"
```
to `c_cpp_properties.json`. It gets in the way if I use meson. I am fine with manually tuning `c_cpp_properties.json` for meson projects, it requires minimum effort, really. However, `configurationProvider` ruins everything, IntelliSense ignores `compile_commands.json` and doesn't work.

**Comment by intractabilis** [comment]
It seems like the problem was that one has to build both release and debug configurations in order for IntelliSense to kick in.

**Comment by ilg-ul** [comment]
Right, IntelliSense needs the `c_cpp_properties.json` for the active configuration to kick in.

**Comment by ilg-ul** [comment]
Is there a better choice for meson projects?

**Comment by intractabilis** [comment]
> Right, IntelliSense needs the `c_cpp_properties.json` for the active configuration to kick in.

What is "active" configuration? I didn't know VS Code has a way to set an active configuration for IntelliSense. How do you do it?

> Is there a better choice for meson projects?

What do you mean? A better choice of what?

**Comment by ilg-ul** [comment]
> What is "active" configuration?

The C/C++ extension, which parses the `.vscode/c_cpp_properties.json` file, has a way of selecting one of the configurations (debug/release), for the indexer to know which `compile_commands.json` to parse.

VS Code shows the active configuration name on the status bar, and you can change it from there.

>  A better choice of what?

A better choice to `"configurationProvider": "ms-vscode.cmake-tools"`.

In my opinion it parses the `compile_commands.json` pretty well, regardless the actual system build generator (CMake/meson/etc).

**Comment by intractabilis** [comment]
> has a way of selecting one of the configurations

Wow, didn't know that. It's really tiny, shoved away from user's attention.

> A better choice to `"configurationProvider": "ms-vscode.cmake-tools"`.

You don't need it at all. It's not what parses `compile_commands.json`. It just tells the language server a few things like the compiler path, IntelliSense mode, etc. Basically it's meant for the cases where you delegate the active configuration switch to an extension. In case of `cmake-tools` you can omit `c_cpp_properties.json`, and the former will provide IntelliSense with the location of the compiler, `compile_commands.json`, and other options. Since you are using `c_cpp_properties.json`, you don't need a configuration provider. Here is an example of `c_cpp_properties.json` for a meson project that works perfectly well:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/my/own/tool/set/for/example/bin/g++",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by ilg-ul** [comment]
I'm not so sure, the compile_commands.json might not be used at all in your case, since you already tell IntelliSense where the compiler is, headers, defines, etc.

Create a dual configuration project with the Hello World template and switch between the two configs; the editor will mark dead code correctly as gray; then use your style of configuration (without provider) and see if switching configs also changes the display.

**Comment by intractabilis** [comment]
> I'm not so sure, the `compile_commands.json` might not be used at all in your case, since you already tell IntelliSense where the compiler is, headers, defines, etc.

I am absolutely, 100% sure. It would have been really strange if you needed to install CMake tools in order for the IntelliSense to operate. It works well without any "providers". What do you mean I told IntelliSense where the headers and what the defines are? Where? You assume my programs use only system headers? My programs go far beyond Hello World, believe me. Turn on debug logging for the cpp extension, and you will see how VS Code sends information from `compile_commands.json` to the language server for each individual file. It does it without any "providers".

> Create a dual configuration project with the Hello World template

Sorry, I am not debugging your template. I have my own projects that do work. I would like to ensure you, IntelliSense works perfectly without any "providers".

**Comment by intractabilis** [comment]
I attached a fully working project example based on your template to a new issue. You can compile it, then turn off CMake tools and xPack extensions, remove `configurationProvider`, restart VS Code, reset IntelliSense database and see that IntelliSense still works correctly and everywhere. The shaded areas of inactive code will change accordingly to the Debug/Release configuration changes.

P.S. "Dead code" is the code that is executed, but its result is not being used.

**Comment by ilg-ul** [comment]
I checked and you were right, VS Code C/C++ parses the `compile_commands.json` files even without a `configurationProvider`, which is nice.

I updated the code to no longer add `configurationProvider` to `c_cpp_properties.json` and published v0.4.14.

Thank you for your contribution to improve the project!

**Comment by intractabilis** [comment]
Yay! No problem. I like this project. It's simple, yet has a lot of power in managing the builds. I am switching my projects to Meson + xPack. I am tired of CMake and CMake tools extension.

**Comment by ilg-ul** [comment]
Great, thank you!

And, if you liked the project, perhaps you can rate it on the Marketplace.

Looking forward to your future contributions.
