### ISSUE TITLE
Specify environment to run `node`

### ISSUE THREAD

**Issue by intractabilis** [xpack/vscode-xpack-extension-ts#20]
I have a feature request. Let me describe the problem first. I have to work with different toolsets. For example, a client might require for a program to be compiled with GCC 8.3. So I build GCC 8.3 and all libraries I need to a separate location. Then I set `PATH`, `LD_LIBRARY_PATH`, `LIBRARY_PATH`, `PKG_CONFIG_PATH`, etc., relative to that location and start VS Code from that environment.

The problem is that `node` that executes `xpm` doesn't run in this environment, because `node` depends on the system's `libstdc++.so`, when it gets a `libstdc++.so` from my development toolset, it complains about the library version mismatch and exits.

I think a solution could be to add a configuration option to specify environment variables to run `node` when it executes `xpm`.

**Comment by ilg-ul** [comment]
Yeah, welcome to the Linux shared libraries hell! :-(

If I understand it right, you suggest to add a way to define a map of named values to be passed to the environment when `xpm run` is executing actions?

The first problem I foresee is that this map most probably will include absolute paths, and thus cannot be stored in `package.json`, which is expected to be cross-platform portable.

Given my experience with building standalone cross-platform binary xPacks, I would say that the build procedure for your custom toolchain needs more work.

BTW, I'm also providing an xPack GCC, exactly for applications that require a specific version. And `xpm` allows to define specific dependencies for each build configuration, which means you can run tests with different toolchains in the same project.

**Comment by intractabilis** [comment]
I am not sure why anything should be stored in `package.json`. I suggest adding options, empty by default, that a user can change in `settings.json` if she wants.

**Comment by ilg-ul** [comment]
It looks like you want to run the `node` process with one set of environment variables and each action in another environment. Is this so?

Please note that `xpm` is a JavaScript code executed by `node` in its context, so when you set any environment variable for `node`, it'll be automatically inherited by `xpm`, and passed in the environment of the process that executes the actions. 

`xpm` itself can do nothing to control the environment for `node` (it is the other way around); all `xpm` can do is to control the environment for running the actions, based on the definitions it gets in `package.json`; `xpm` does not know about `setting.json`, and `xpm` should be able to run independently of VS Code.

The extension can read definitions from `settings.json` and pass them to the environment before calling xpm, but this environment will also be inherited by all actions.

So if you have a proposal on how the extension should behave, please try to explain it to me in more detail.

**Comment by intractabilis** [comment]
Ah, of course, you are right. I could have thought about it myself. Let's forget about it. I'll just compile `node` for each toolset.

**Comment by ilg-ul** [comment]
> I'll just compile node for each toolset

As you wish, but this does not seem to scale and does not really solve the shared libraries hell.

Can you share your thoughts why using the [xPack GCC](https://github.com/xpack-dev-tools/gcc-xpack) does not meet your needs?

Right now I'm working on clang 11 & 12, and I'll soon add gcc 9, 10, 11, so you'll have all major releases easily available as xpm dependencies.

**Comment by intractabilis** [comment]
You mean these compiled toolsets already include `node` binary? I am not sure how it works.

Besides a toolset itself, I need around 30 other libraries with it. I compile them anyway for a specific toolset. Compiling `node` in addition doesn't make much of a difference.

**Comment by ilg-ul** [comment]
> You mean these compiled toolsets already include node binary?

Nope. Why would it need to include the node binary?

> I am not sure how it works.

It is very easy, just create a hello world project with template, as described in the extension README, build it and run it.

Everything works without having to set any environment variables. Everything works on any platform, including CI servers, like GitHub Actions, Travis, etc.
