### ISSUE TITLE
vscode 1.58 + xpack ext 0.4.14 not work

### ISSUE THREAD

**Issue by linquize** [xpack/vscode-xpack-extension-ts#21]
vscode 1.58 + xpack ext 0.4.14 not work
It was working in vscode 1.57.1

**Comment by ilg-ul** [comment]
I'll investigate.

**Comment by ilg-ul** [comment]
I just created a Hello World project with the project template, installed dependencies and built both configurations.

Can you be more specific on what did not work in your setup?

**Comment by linquize** [comment]
xpack panel only has package.json.
install action is not added.
any custom actions are not added.
clicking new button has no response.

**Comment by ilg-ul** [comment]
I checked on macOS, Windows, and Raspberry Pi OS and they seem ok.

Only on an Ubuntu I noticed several problems, which I'll investigate.

Can you provide more details about your environment?

**Comment by linquize** [comment]
Win10

```json
{
  ..........
  "xpack": {
    "minimumXpmRequired": "0.10.1",
    "actions": {
      "build": "make",
      "clean": "make clean"
    }
  }
}
```

**Comment by ilg-ul** [comment]
I confirm your issue, for yet unknown reasons the xPack Actions explorer tree does not initialise properly.

I'll investigate, but until a fix will be available, the workaround is to manually press the Refresh icon, which should redraw the tree correctly.

**Comment by ilg-ul** [comment]
The issue was identified as a race condition in preparing the tree items to be shown in the xPack explorer; the fix was a simple code reorder.

Tomorrow I'll do some more tests and hopefully make a new release.

**Comment by ilg-ul** [comment]
Please check the new release and let me know if it works on your machine.

**Comment by linquize** [comment]
0.4.14 works with vscode 1.58.1.
Thanks!

**Comment by ilg-ul** [comment]
You're welcome!

Thank you for helping improve this project.
