### ISSUE TITLE
Publish to open VSX

### ISSUE THREAD

**Issue by 0Grit** [xpack/vscode-xpack-extension-ts#25]
https://open-vsx.org/

I use the gitpod.io service which can pull from the openvsx registry.
I can manually install the vsx from the VS Code marketplace but that is less ideal than having it built into gitpod's native registry.

**Comment by 0Grit** [comment]
Alternatively or until you get it published to openvsx; If you could release it here on github as a .vsx file that way I can just use the github release link to install it directly to my gitpod workspace.

**Comment by ilg-ul** [comment]
Hi Garrett, if I understand it right, you suggest to publish this extension to alternate registries?

**Comment by 0Grit** [comment]
Correct. The licensing for the VS Code registry doesn't allow any software besides Microsoft's official VS Code releases to interact with the registry. Or something like that. I use gitpod.io 's built in editor based on vs Code which uses Open VSX as it's registry.

**Comment by 0Grit** [comment]
https://www.gitpod.io/docs/vscode-extensions

![image](https://user-images.githubusercontent.com/24318071/143437250-4d492ff6-7736-4499-a8eb-9055ffdb9b8d.png)

**Comment by 0Grit** [comment]
Sorry for all the posts, I'm still half asleep;

It can take a couple days to get ownership of a namespace in the open vsx registry so a solution until then would be to release this extension on github as a .vsix file.

![image](https://user-images.githubusercontent.com/24318071/143437588-df545905-354a-4cf1-9617-57d2030d6fdf.png)

**Comment by ilg-ul** [comment]
I published a new release:

- https://github.com/xpack/vscode-xpack-extension-ts/releases/tag/v0.4.16

**Comment by ilg-ul** [comment]
As for the openvsx registry, I probably need to take some time to understand what it is and how it can be used.

But, for my information, why would someone not use VS Code directly and prefer alternate solutions which require alternate registries?

**Comment by 0Grit** [comment]
Mircosoft doesn't allow unofficial VS Code builds to use their registry.

**Comment by ilg-ul** [comment]
> Mircosoft doesn't allow unofficial VS Code builds to use their registry.

What I'm trying to understand is what other unofficial builds should be considered, and if possible, why they exist, why the official build is not enough?

**Comment by 0Grit** [comment]
https://www.gitpod.io/blog/open-vsx

**Comment by ilg-ul** [comment]
I logged in to Open VSX, I signed the publisher agreement, I created the publish authentication token, but when I tried to publish the extension, it failed, for obvious reasons:

```console
...
webpack 5.49.0 compiled with 1 warning in 3478 ms
 DONE  Packaged: /var/folders/3h/98gc9hrn3qnfm40q7_0rxczw0000gn/T/tmp-66568-JU75BEA1vsX4-.vsix (10 files, 108.84KB)

❌  Cannot resolve dependency: ms-vscode.cpptools
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

The xPack extension obviously makes use of the MS C++ extension, which is available only from the VS Code Marketplace.

Sorry to say, but I maintain my bad impression of all these jolly joker pseudo-solutions.

**Comment by 0Grit** [comment]
Thanks for trying. I should have realized this would be an issue.

Feel free to close, adding the .vsix to the release is sufficient for my experiments.
