### ISSUE TITLE
Comments in c_cpp_properties.json

### ISSUE THREAD

**Issue by nicreuss** [xpack/vscode-xpack-extension-ts#38]
# Standard behaviour
When an additional configuration is added to the `package.json` file, the xpack-extension updates `c_cpp_properties.json` with the additional config as described [here](https://xpack.github.io/vscode/quick-start/).

Note that additional configuration details in `c_cpp_properties.json` are preserved (like `configurationProvider` in the example below).

```json
{
  "configurations": [
    {
      "name": "wb55rg-nucleo.debug",
      "configurationProvider": "ms-vscode.makefile-tools"
    },
    {
      "name": "new_config"
    }
  ],
  "version": 4
}
```

# Abnormal behaviour
The `c_cpp_properties.json` file supports "JSON with comments". 

```json
{
  // A comment
  "configurations": [
    {
      "name": "wb55rg-nucleo.debug",
      "configurationProvider": "ms-vscode.makefile-tools"
    }
  ],
  "version": 4
}

```

Consider the case where there is a comment in `c_cpp_properties.json` file and an update is made to package.json. The extension removes all comments and additional configuration details:

```json
{
  "configurations": [
    {
      "name": "wb55rg-nucleo.debug"
    },
    {
      "name": "new_config"
    }
  ],
  "version": 4
}

```

Once would expect the additional configuration data to always be preserved. Preserving the comments might prove to be difficult.

**Comment by ilg-ul** [comment]
> Preserving the comments might prove to be difficult.

Indeed!

The extension reads the file with the standard json parser, adds new content, writes it back. If we need to preserve comments, I guess a different parser/serializer should be used.

Any suggestion?

**Comment by ilg-ul** [comment]
I found an interface `JSONScanner` in the VSCode source, which seems to do the trick.

Unfortunately it is not that simple, it'll take a while to understand it. :-(

**Comment by nicreuss** [comment]
> Any suggestion?

I haven't worked with anything that supports comments yet.

I think the main problem is that any comment in the file causes properties in the json to be lost. Even if we drop comments from the file but preserve the existing configurations, that might be a good start.

**Comment by ilg-ul** [comment]
As said before, the current code uses the standard JSON parser. I did not try, but I would guess that the standard parser simply crashes when a comment is encountered.

If I understand it right, it would be a bit better to replace it with a parser that ignores the comments and returns the content.

This might be easier to do than using the VS Code internal parser, which is very, very complicated.

**Comment by ilg-ul** [comment]
One possible parser to be evaluated is [json5](https://github.com/json5/json5).

**Comment by ilg-ul** [comment]
I gave JSON5 a try. Unfortunately it is not a direct replacement of the standard JSON. It parses files with comments, but it outputs the files in JSON5 format, not in standard JSON (for example keys are no longer quoted), and this breaks compatibility with VS Code.

Things are not simple... :-(

**Comment by nicreuss** [comment]
It looks like the vscode [C/C++ Extension](https://github.com/microsoft/vscode-cpptools) uses the [comment-json](https://www.npmjs.com/package/comment-json) package.

These 2 lines seem relevant:
- https://github.com/microsoft/vscode-cpptools/blob/5e9676546773b994092eba783f79d398568e811b/Extension/src/LanguageServer/configurations.ts#L18
- https://github.com/microsoft/vscode-cpptools/blob/5e9676546773b994092eba783f79d398568e811b/Extension/src/LanguageServer/configurations.ts#L1288

**Comment by ilg-ul** [comment]
Fixed in 0.4.22 on 2023-02-16.

@nicreuss, please give it a try.

**Comment by nicreuss** [comment]
I've done some testing using v0.4.22 and it seems to be working. Thank you so much for this feature!

**Comment by ilg-ul** [comment]
Thank you for your help!
