### ISSUE TITLE
Fix c_cpp_properties.json line terminator

### ISSUE THREAD

**Issue by ilg-ul** [xpack/vscode-xpack-extension-ts#42]
Check the logic to update `c_cpp_properties.json`, to avoid rewriting it if not necessary.

**Comment by pur-jus** [comment]
Hi Liviu,

Effectively, I observe that the `c_cpp_properties.json` file is rewritten at each save of the `packages.json`...

...And trig a line ending modification of the last line:
I work on Windows but I save my files with UNIX line ending. Each time that `package.json` is saved, the line ending format of the last line of the `c_cpp_properties.json` file is modificated. From LF to CRLF.

**Comment by ilg-ul** [comment]
> the c_cpp_properties.json file is rewritten at each save of the packages.json.

That's correct, it must reflect the possible changes in build configurations.

>  the line ending format of the last line of the c_cpp_properties.json file is modificated. From LF to CRLF.

Yes, this is  weird, the JSON serialiser uses only LF, even on Windows, and my code adds the portable definition `os.EOL`, which on Windows is CRLF.

I fixed the line termination, now it is a single LF, please upgrade to 0.5.2.

**Comment by ghost** [comment]
Thank you Liviu, it works fine 🙏

**Comment by ilg-ul** [comment]
Great, thank you for confirming.
